/*
 * user_logic_registers.c
 *
 *  Created on: Oct 31, 2016
 *      Author: Burak
 */

#include "logic_reg_if.h"
#include "xparameters.h"
#include "xil_io.h"
#include "stdlib.h"
#include "math.h"
#include "aux_func.h"
#include "ext_if.h"


unsigned int read_fpga_register(unsigned int regAddr)
{
	return Xil_In32(USER_LOGIC_REG_IF_BASE_ADDR+regAddr);
}

void read_user_register(unsigned int registerAddr, unsigned int* registerValue)
{
	registerValue[0] = Xil_In32(USER_LOGIC_REG_IF_BASE_ADDR+registerAddr);
}

void write_user_register(unsigned int registerAddr, unsigned int registerValue)
{
	Xil_Out32(USER_LOGIC_REG_IF_BASE_ADDR + registerAddr, registerValue);
}

void init_user_registers(void)
{
	ETH_TESTER_ENABLE[0] = 0;

	//UART
	u32 clkDivBaud = 0;
	clkDivBaud = (u32)(CLK_FREQ/UART_BAUD_RATE);
	EXT_INTERFACE_CLK_DIV_BAUD[0] = clkDivBaud;

	ETH_MAC_SPEED[0] = 0x2;
	ETH_IF_RST[0] = 1;
	lSleep(1000);
	ETH_IF_RST[0] = 0;

	//PHY IF
	EXT_INTERFACE_PHY_IF_WAIT_IN[0] 			= PHY_IF_WAIT_IN;
	EXT_INTERFACE_PHY_IF_DEBOUNCE[0] 			= PHY_IF_DEBOUNCE;
	EXT_INTERFACE_PHY_IF_R_TIMEOUT[0] 			= PHY_IF_R_TIMEOUT;
	EXT_INTERFACE_PHY_IF_E_RESPONSE_TIMEOUT[0] 	= PHY_IF_E_RESPONSE_TIMEOUT;
	EXT_INTERFACE_PHY_IF_E_REQUEST_TIMEOUT[0] 	= PHY_IF_E_REQUEST_TIMEOUT;
	EXT_INTERFACE_PHY_IF_COMPENSATION_COUNT[0]	= PHY_IF_COMPENSATION_COUNT;
	EXT_INTERFACE_PHY_IF_DATA_OUT_SELECT[0]		= NORMAL_MODE; //ADDRESS_MODE NORMAL_MODE

	//for enabled packets, related bit which index respected to field bus value must be set to 1
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_255_224[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_223_192[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_191_160[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_159_128[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_127_96[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_95_64[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_63_32[0]	= 0xFFFFFFFF;
	//EXT_INTERFACE_PHY_IF_PACKET_ENABLE_31_0[0]	= 0xFFFFFFFF;

	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_255_224[0]	= 0x80010009;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_223_192[0]	= 0x00000030;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_191_160[0]	= 0x00000000;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_159_128[0]	= 0x00000000;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_127_96[0]	= 0x00000000;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_95_64[0]		= 0x000007C4;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_63_32[0]		= 0x00000004;
	EXT_INTERFACE_PHY_IF_PACKET_ENABLE_31_0[0]		= 0x00000000;

	//EMU
	PHY_BUS_MUX_CTRL[0] = RADAR_MODE;
	EMU_E_WAIT_COUNTER[0] = EMU_E_WAIT_COUNTER_REG; // 0x500000; //3D0900
	EMU_PACKET_WAIT_COUNTER[0] = EMU_PACKET_WAIT_COUNTER_REG; // 0x3D0900;

}

void loadEthSettings(void)
{
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_5_MSB_IDX; 	ETH_REG_WR_DATA[0] = getEthSettings()->srcMacAddr[0];
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_4_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->srcMacAddr[1];
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_3_IDX;	 		ETH_REG_WR_DATA[0] = getEthSettings()->srcMacAddr[2];
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_2_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->srcMacAddr[3];
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_1_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->srcMacAddr[4];
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_0_LSB_IDX; 	ETH_REG_WR_DATA[0] = getEthSettings()->srcMacAddr[5];

	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_3_MSB_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->srcIpAddr[0];
	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_2_IDX; 			ETH_REG_WR_DATA[0] = getEthSettings()->srcIpAddr[1];
	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_1_IDX; 			ETH_REG_WR_DATA[0] = getEthSettings()->srcIpAddr[2];
	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_0_LSB_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->srcIpAddr[3];

	ETH_REG_WR_IDX[0] = UDP_SRC_PORT_MSB_IDX;			ETH_REG_WR_DATA[0] = getEthSettings()->srcPort[0];
	ETH_REG_WR_IDX[0] = UDP_SRC_PORT_LSB_IDX;			ETH_REG_WR_DATA[0] = getEthSettings()->srcPort[1];

	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_5_MSB_IDX; 	ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestMacAddr[0];
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_4_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestMacAddr[1];
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_3_IDX;	 	ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestMacAddr[2];
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_2_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestMacAddr[3];
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_1_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestMacAddr[4];
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_0_LSB_IDX; 	ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestMacAddr[5];

	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_3_MSB_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestIpAddr[0];
	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_2_IDX; 			ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestIpAddr[1];
	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_1_IDX; 			ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestIpAddr[2];
	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_0_LSB_IDX; 		ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestIpAddr[3];

	ETH_REG_WR_IDX[0] = UDP_DEST_PORT_MSB_IDX;			ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestPort[0];
	ETH_REG_WR_IDX[0] = UDP_DEST_PORT_LSB_IDX;			ETH_REG_WR_DATA[0] = getEthSettings()->multicastDestPort[1];

}

void loadEthFactoryDefaults(void)
{
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_5_MSB_IDX; 	ETH_REG_WR_DATA[0] = DEFAULT_ETH_SRC_MAC_ADDR_5_MSB; 	getEthSettings()->srcMacAddr[0] = DEFAULT_ETH_SRC_MAC_ADDR_5_MSB;
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_4_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_SRC_MAC_ADDR_4;		getEthSettings()->srcMacAddr[1] = DEFAULT_ETH_SRC_MAC_ADDR_4;
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_3_IDX;	 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_SRC_MAC_ADDR_3;		getEthSettings()->srcMacAddr[2] = DEFAULT_ETH_SRC_MAC_ADDR_3;
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_2_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_SRC_MAC_ADDR_2;		getEthSettings()->srcMacAddr[3] = DEFAULT_ETH_SRC_MAC_ADDR_2;
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_1_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_SRC_MAC_ADDR_1;		getEthSettings()->srcMacAddr[4] = DEFAULT_ETH_SRC_MAC_ADDR_1;
	ETH_REG_WR_IDX[0] = ETH_SRC_MAC_ADDR_0_LSB_IDX; 	ETH_REG_WR_DATA[0] = DEFAULT_ETH_SRC_MAC_ADDR_0_LSB;	getEthSettings()->srcMacAddr[5] = DEFAULT_ETH_SRC_MAC_ADDR_0_LSB;

	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_5_MSB_IDX; 	ETH_REG_WR_DATA[0] = DEFAULT_ETH_DEST_MAC_ADDR_5_MSB;	getEthSettings()->multicastDestMacAddr[0] = DEFAULT_ETH_DEST_MAC_ADDR_5_MSB;
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_4_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_DEST_MAC_ADDR_4;		getEthSettings()->multicastDestMacAddr[1] = DEFAULT_ETH_DEST_MAC_ADDR_4;
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_3_IDX;	 	ETH_REG_WR_DATA[0] = DEFAULT_ETH_DEST_MAC_ADDR_3;		getEthSettings()->multicastDestMacAddr[2] = DEFAULT_ETH_DEST_MAC_ADDR_3;
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_2_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_DEST_MAC_ADDR_2;		getEthSettings()->multicastDestMacAddr[3] = DEFAULT_ETH_DEST_MAC_ADDR_2;
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_1_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_ETH_DEST_MAC_ADDR_1;		getEthSettings()->multicastDestMacAddr[4] = DEFAULT_ETH_DEST_MAC_ADDR_1;
	ETH_REG_WR_IDX[0] = ETH_DEST_MAC_ADDR_0_LSB_IDX; 	ETH_REG_WR_DATA[0] = DEFAULT_ETH_DEST_MAC_ADDR_0_LSB;	getEthSettings()->multicastDestMacAddr[5] = DEFAULT_ETH_DEST_MAC_ADDR_0_LSB;

	ETH_REG_WR_IDX[0] = ETH_TYPE_MSB_IDX; 				ETH_REG_WR_DATA[0] = DEFAULT_ETH_TYPE_MSB;
	ETH_REG_WR_IDX[0] = ETH_TYPE_LSB_IDX; 				ETH_REG_WR_DATA[0] = DEFAULT_ETH_TYPE_LSB;

	ETH_REG_WR_IDX[0] = IP_VERSION_IDX; 				ETH_REG_WR_DATA[0] = DEFAULT_IP_VERSION;
	ETH_REG_WR_IDX[0] = IP_HEADER_LENGTH_IDX; 			ETH_REG_WR_DATA[0] = DEFAULT_IP_HEADER_LENGTH;
	ETH_REG_WR_IDX[0] = IP_SERVICE_IDX; 				ETH_REG_WR_DATA[0] = DEFAULT_IP_SERVICE;

	ETH_REG_WR_IDX[0] = IP_LENGTH_MSB_IDX; 				ETH_REG_WR_DATA[0] = DEFAULT_IP_LENGTH_MSB;
	ETH_REG_WR_IDX[0] = IP_LENGTH_LSB_IDX; 				ETH_REG_WR_DATA[0] = DEFAULT_IP_LENGTH_LSB;

	ETH_REG_WR_IDX[0] = IP_DATAGRAM_ID_MSB_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_IP_DATAGRAM_ID_MSB;
	ETH_REG_WR_IDX[0] = IP_DATAGRAM_ID_LSB_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_IP_DATAGRAM_ID_LSB;

	ETH_REG_WR_IDX[0] = IP_FLAGS_IDX;					ETH_REG_WR_DATA[0] = DEFAULT_IP_FLAGS;

	ETH_REG_WR_IDX[0] = IP_FRAGMENT_OFFSET_MSB_IDX;		ETH_REG_WR_DATA[0] = DEFAULT_IP_FRAGMENT_OFFSET_MSB;
	ETH_REG_WR_IDX[0] = IP_FRAGMENT_OFFSET_LSB_IDX;		ETH_REG_WR_DATA[0] = DEFAULT_IP_FRAGMENT_OFFSET_LSB;

	ETH_REG_WR_IDX[0] = IP_TIMETOLIVE_IDX;				ETH_REG_WR_DATA[0] = DEFAULT_IP_TIMETOLIVE;
	ETH_REG_WR_IDX[0] = IP_PROTOCOL_IDX;				ETH_REG_WR_DATA[0] = DEFAULT_IP_PROTOCOL;

	ETH_REG_WR_IDX[0] = IP_HEADER_CHECKSUM_MSB_IDX;		ETH_REG_WR_DATA[0] = DEFAULT_IP_HEADER_CHECKSUM_MSB;
	ETH_REG_WR_IDX[0] = IP_HEADER_CHECKSUM_LSB_IDX;		ETH_REG_WR_DATA[0] = DEFAULT_IP_HEADER_CHECKSUM_LSB;

	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_3_MSB_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_IP_SRC_IP_ADDR_3_MSB;		getEthSettings()->srcIpAddr[0] = DEFAULT_IP_SRC_IP_ADDR_3_MSB;
	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_2_IDX; 			ETH_REG_WR_DATA[0] = DEFAULT_IP_SRC_IP_ADDR_2;			getEthSettings()->srcIpAddr[1] = DEFAULT_IP_SRC_IP_ADDR_2;
	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_1_IDX; 			ETH_REG_WR_DATA[0] = DEFAULT_IP_SRC_IP_ADDR_1;			getEthSettings()->srcIpAddr[2] = DEFAULT_IP_SRC_IP_ADDR_1;
	ETH_REG_WR_IDX[0] = IP_SRC_IP_ADDR_0_LSB_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_IP_SRC_IP_ADDR_0_LSB;		getEthSettings()->srcIpAddr[3] = DEFAULT_IP_SRC_IP_ADDR_0_LSB;

	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_3_MSB_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_IP_DEST_IP_ADDR_3_MSB;		getEthSettings()->multicastDestIpAddr[0] = DEFAULT_IP_DEST_IP_ADDR_3_MSB;
	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_2_IDX; 			ETH_REG_WR_DATA[0] = DEFAULT_IP_DEST_IP_ADDR_2;			getEthSettings()->multicastDestIpAddr[1] = DEFAULT_IP_DEST_IP_ADDR_2;
	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_1_IDX; 			ETH_REG_WR_DATA[0] = DEFAULT_IP_DEST_IP_ADDR_1;			getEthSettings()->multicastDestIpAddr[2] = DEFAULT_IP_DEST_IP_ADDR_1;
	ETH_REG_WR_IDX[0] = IP_DEST_IP_ADDR_0_LSB_IDX; 		ETH_REG_WR_DATA[0] = DEFAULT_IP_DEST_IP_ADDR_0_LSB;		getEthSettings()->multicastDestIpAddr[3] = DEFAULT_IP_DEST_IP_ADDR_0_LSB;

	ETH_REG_WR_IDX[0] = UDP_SRC_PORT_MSB_IDX;			ETH_REG_WR_DATA[0] = DEFAULT_UDP_SRC_PORT_MSB;			getEthSettings()->srcPort[0] = DEFAULT_UDP_SRC_PORT_MSB;
	ETH_REG_WR_IDX[0] = UDP_SRC_PORT_LSB_IDX;			ETH_REG_WR_DATA[0] = DEFAULT_UDP_SRC_PORT_LSB;			getEthSettings()->srcPort[1] = DEFAULT_UDP_SRC_PORT_LSB;

	ETH_REG_WR_IDX[0] = UDP_DEST_PORT_MSB_IDX;			ETH_REG_WR_DATA[0] = DEFAULT_UDP_DEST_PORT_MSB;			getEthSettings()->multicastDestPort[0] = DEFAULT_UDP_DEST_PORT_MSB;
	ETH_REG_WR_IDX[0] = UDP_DEST_PORT_LSB_IDX;			ETH_REG_WR_DATA[0] = DEFAULT_UDP_DEST_PORT_LSB;			getEthSettings()->multicastDestPort[0] = DEFAULT_UDP_DEST_PORT_LSB;

	ETH_REG_WR_IDX[0] = UDP_LENGTH_MSB_IDX;				ETH_REG_WR_DATA[0] = DEFAULT_UDP_LENGTH_MSB;
	ETH_REG_WR_IDX[0] = UDP_LENGTH_LSB_IDX;				ETH_REG_WR_DATA[0] = DEFAULT_UDP_LENGTH_LSB;

	ETH_REG_WR_IDX[0] = UDP_CHECKSUM_MSB_IDX;			ETH_REG_WR_DATA[0] = DEFAULT_UDP_CHECKSUM_MSB;
	ETH_REG_WR_IDX[0] = UDP_CHECKSUM_LSB_IDX;			ETH_REG_WR_DATA[0] = DEFAULT_UDP_CHECKSUM_LSB;
}


